
-- 1번 문제
-- [ 관리자 계정에서 example 계정 생성]
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER example_0111 IDENTIFIED BY "1234qwer";

GRANT CONNECT, RESOURCE TO example_0111;

ALTER USER example_0111 DEFAULT TABLESPACE "A230724"

QUOTA 20M ON "A230724";



ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER example_0222 IDENTIFIED BY "1234qwer";

GRANT CONNECT, CREATE VIEW TO example_0222;

ALTER USER example_0222 DEFAULT TABLESPACE "A230724"

QUOTA 20M ON "A230724";

-----------------------------------------------------------------------------------------
-- 2번 문제

REVOKE CONNECT FROM example_0222;
DROP USER example_0222 CASCADE;

-------------------------------------------------------------------------------------------
-- 3번 문제
-- [example_0111계정으로 접속]

CREATE TABLE MEMBER (
 MEMBER_NO NUMBER PRIMARY KEY,
 MEMBER_ID VARCHAR2(30) NOT NULL,
 MEMBER_PASSWORD VARCHAR2(30) NOT NULL,
 PHONE_NUMBER VARCHAR2(20), 
 DELETE_YN CHAR(1) DEFAULT 'N',
 
 CHECK(DELETE_YN IN ('Y','N')) 

);

COMMENT ON COLUMN MEMBER.MEMBER_NO  IS '회원번호';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PASSWORD IS '비밀번호';
COMMENT ON COLUMN MEMBER.PHONE_NUMBER IS '핸드폰번호';
COMMENT ON COLUMN MEMBER.DELETE_YN IS '삭제여부';


CREATE TABLE BOARD( 
 BOARD_NO NUMBER PRIMARY KEY,
 BOARD_TITLE VARCHAR2(300) NOT NULL,
 BOARD_CONTENT VARCHAR2(4000) NOT NULL,
 BOARD_WRITER NUMBER REFERENCES MEMBER(MEMBER_NO),
 CREATE_DATE DATE DEFAULT SYSDATE
 
);

COMMENT ON COLUMN BOARD.BOARD_NO  IS '글번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '글제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '글내용';
COMMENT ON COLUMN BOARD.BOARD_WRITER IS '작성자';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '작성일자';

------------------------------------------------------------------------------------
-- 04번

-- 시퀀스 생성
-- SEQ_MEMBER_NO
CREATE SEQUENCE SEQ_MEMBER_NO
START WITH 100 
INCREMENT BY 100 
;

-- 시퀀스 생성
-- SEQ_BOARD_NO
CREATE SEQUENCE SEQ_BOARD_NO
START WITH 1
INCREMENT BY 1 
;

-- 테이블 추가 
--MEMBER 테이블

INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL,'step1', 'step11', NULL, DEFAULT);
INSERT INTO MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL,'step2', 'step22', '010-1111-2222', DEFAULT);
INSERT INTO MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL,'step3', 'step33', NULL, DEFAULT);

SELECT * FROM MEMBER;


-- 테이블 추가
-- BOARD 테이블

INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'첫 글', '스텝평가', '100', DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'두 번째 글', '재밌다', '300', DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'세 번째 글', '하하하', '200', DEFAULT);

SELECT * FROM BOARD;

----------------------------------------------------------------------------------------------

-- 5번 문제

SELECT BOARD_NO 글번호, BOARD_TITLE 제목, BOARD_CONTENT 내용, MEMBER_ID 작성자, CREATE_DATE 작성일자
FROM BOARD 
JOIN MEMBER ON(BOARD_WRITER = MEMBER_NO)
ORDER BY BOARD_NO DESC;


